apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
spec:
  destination:
    name: 'in-cluster'
    namespace: argocd
  source:
    path: helm/my-nginx
    repoURL: 'https://gitlab.nw18devops.com/devops/nw18-argocd-helm-files.git'
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
